version: '3'

services:
  redis:
    image: redis:latest
    container_name: redis_soffia
    restart: always
    ports:
      - "6379:6379"

  db:
    image: postgres
    container_name: postgres_soffia
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"

volumes:
  pgdata:
